from __future__ import annotations

import numpy as np
from scipy.optimize import minimize_scalar

from ..optics.refractive_index import corrected_wavenumber
from ..types import FitResult, ProcessedSpectrum


def _profile_dataset(
    spectrum: ProcessedSpectrum,
    n_layer: np.ndarray,
    thickness_um: float,
    max_harmonic: int,
    stride: int = 1,
):
    """Profile a truncated Fourier/Airy surrogate at a fixed thickness.

    K=1 is the ordinary double-beam sinusoid.  K>=2 permits the higher
    harmonics generated by repeated internal reflections, while preserving one
    shared fundamental optical thickness.  Slow linear background and amplitude
    drift are profiled out for each quadrature.
    """
    if max_harmonic < 1:
        raise ValueError("max_harmonic 必须至少为 1。")
    sl = slice(None, None, max(1, int(stride)))
    wn = spectrum.wavenumber_cm1[sl]
    y = spectrum.normalized[sl]
    n = np.asarray(n_layer)[sl]
    x = corrected_wavenumber(wn, n, spectrum.raw.angle_deg)
    t = 2.0 * (wn - wn.min()) / max(np.ptp(wn), 1.0) - 1.0
    d_cm = float(thickness_um) * 1e-4
    phi = 4.0 * np.pi * d_cm * x

    columns = [np.ones_like(t), t]
    names = ["offset", "linear_background"]
    for k in range(1, int(max_harmonic) + 1):
        c = np.cos(k * phi)
        s = np.sin(k * phi)
        columns.extend([c, s, t * c, t * s])
        names.extend([
            f"cos_{k}", f"sin_{k}", f"linear_cos_{k}", f"linear_sin_{k}"
        ])
    design = np.column_stack(columns)
    coef, *_ = np.linalg.lstsq(design, y, rcond=None)
    fitted = design @ coef
    return fitted, coef, names, y


def _objective(
    spectra: list[ProcessedSpectrum],
    n_arrays: list[np.ndarray],
    thickness_um: float,
    max_harmonic: int,
    stride: int,
) -> float:
    total = 0.0
    for spec, n in zip(spectra, n_arrays):
        fitted, _, _, y = _profile_dataset(
            spec, n, thickness_um, max_harmonic=max_harmonic, stride=stride
        )
        residual = y - fitted
        scale = 1.4826 * np.median(np.abs(y - np.median(y))) + 1e-12
        total += float(np.sum((residual / scale) ** 2))
    return total


def fit_joint_harmonic(
    spectra: list[ProcessedSpectrum],
    n_functions: list,
    initial_thickness_um: float,
    thickness_bounds_um: tuple[float, float],
    max_harmonic: int = 3,
) -> FitResult:
    """Joint multi-angle harmonic fit with one shared fundamental thickness.

    This is an empirical Airy surrogate.  It is useful for judging whether a
    K=1 double-beam waveform is sufficient without claiming that unknown
    substrate doping/absorption parameters have been uniquely identified.
    """
    if len(spectra) != len(n_functions):
        raise ValueError("spectra 与 n_functions 长度必须一致。")
    if max_harmonic < 1:
        raise ValueError("max_harmonic 必须至少为 1。")

    lo, hi = map(float, thickness_bounds_um)
    initial = float(np.clip(initial_thickness_um, lo, hi))
    n_arrays = [fn(spec.wavenumber_cm1) for spec, fn in zip(spectra, n_functions)]

    # Restrict the search around the robust preliminary consensus so the second
    # or third harmonic cannot be mistaken for the physical fundamental.
    local_lo = max(lo, initial * 0.72)
    local_hi = min(hi, initial * 1.28)
    if local_hi <= local_lo:
        local_lo, local_hi = lo, hi

    grid = np.linspace(local_lo, local_hi, 701)
    scores = np.array([
        _objective(spectra, n_arrays, d, max_harmonic, stride=4) for d in grid
    ])
    best = int(np.argmin(scores))
    left = grid[max(0, best - 4)]
    right = grid[min(len(grid) - 1, best + 4)]
    if right <= left:
        left, right = local_lo, local_hi

    opt = minimize_scalar(
        lambda d: _objective(spectra, n_arrays, float(d), max_harmonic, stride=1),
        bounds=(left, right),
        method="bounded",
        options={"xatol": 1e-9, "maxiter": 500},
    )
    d = float(opt.x)

    fitted_dict: dict[str, np.ndarray] = {}
    residual_dict: dict[str, np.ndarray] = {}
    parameters: dict[str, object] = {
        "max_harmonic": int(max_harmonic),
        "optimizer": "profiled_fourier_scalar_search",
        "fit_domain": "normalized_fringe",
        "search_interval_um": [float(local_lo), float(local_hi)],
    }
    total_n = 0
    total_rss = 0.0
    # Shared d + [offset, trend, 4 coefficients per harmonic] per spectrum.
    total_k = 1 + (2 + 4 * int(max_harmonic)) * len(spectra)
    for spec, n in zip(spectra, n_arrays):
        fitted, coef, names, y = _profile_dataset(
            spec, n, d, max_harmonic=max_harmonic, stride=1
        )
        residual = y - fitted
        fitted_dict[spec.raw.name] = fitted
        residual_dict[spec.raw.name] = residual
        parameters[f"coefficients_{spec.raw.name}"] = {
            name: float(value) for name, value in zip(names, coef)
        }
        total_n += len(residual)
        total_rss += float(np.sum(residual**2))

    rmse = float(np.sqrt(total_rss / max(total_n, 1)))
    bic = float(
        total_n * np.log(total_rss / max(total_n, 1) + 1e-30)
        + total_k * np.log(max(total_n, 1))
    )
    return FitResult(
        method=f"joint_harmonic_k{max_harmonic}",
        thickness_um=d,
        success=bool(opt.success),
        metrics={
            "rmse": rmse,
            "rss": total_rss,
            "bic": bic,
            "objective": float(opt.fun),
            "n_parameters": float(total_k),
        },
        parameters=parameters,
        fitted=fitted_dict,
        residuals=residual_dict,
    )
